// Worker HTTP-facing ingest logic: open an upload, accept one chunk, finalise.
// Wires the pure functions in cleaning.ts to D1, per docs/decisions.md section 4
// (chunking, json_each batch inserts, batch size 500) and section 5 (schema).

// Env comes from the global declared in worker-configuration.d.ts (generated by
// `npm run types` from wrangler.jsonc's d1_databases binding), not hand-rolled here.

export type OpenUploadResult = { uploadId: string };

export async function openUpload(env: Env, filename: string): Promise<OpenUploadResult> {
  const uploadId = crypto.randomUUID();
  await env.DB.prepare(
    `INSERT INTO uploads (id, filename, uploaded_at, status) VALUES (?1, ?2, ?3, 'open')`,
  )
    .bind(uploadId, filename, new Date().toISOString())
    .run();
  return { uploadId };
}
