// Worker HTTP-facing ingest logic: open an upload, accept one chunk, finalise.
// Wires the pure functions in cleaning.ts to D1, per docs/decisions.md section 4
// (chunking, json_each batch inserts, batch size 500) and section 5 (schema).

import { cleanRow, dedupeAccepted, type AcceptedRow, type RejectedRow } from "./cleaning";

// Env comes from the global declared in worker-configuration.d.ts (generated by
// `npm run types` from wrangler.jsonc's d1_databases binding), not hand-rolled here.

// docs/decisions.md section 4: 500 rows/statement keeps a 1,000-row chunk to 2
// insert statements, ~60KB of bound-string per statement against the 2MB cap,
// well inside the 50-query and 100-bound-param-per-statement free tier limits.
const INSERT_BATCH_SIZE = 500;

const INSERT_CHECKS_SQL = `
INSERT OR IGNORE INTO checks (upload_id, service_id, service_name, ts, day, agent,
                              region, status_code, status_class, latency_ms, degraded,
                              corrections)
SELECT ?1,
       json_extract(value, '$.s'), json_extract(value, '$.n'),
       json_extract(value, '$.t'), json_extract(value, '$.d'),
       json_extract(value, '$.a'), json_extract(value, '$.g'),
       json_extract(value, '$.c'), json_extract(value, '$.k'),
       json_extract(value, '$.l'), json_extract(value, '$.x'),
       json_extract(value, '$.f')
FROM json_each(?2)
`;

// Same json_each shape as checks - a chunk that is entirely rejected rows must
// stay within the 50-query budget too, so this cannot be one INSERT per row.
const INSERT_REJECTED_SQL = `
INSERT INTO rejected_rows (upload_id, line_no, raw, reason)
SELECT ?1,
       json_extract(value, '$.n'),
       json_extract(value, '$.r'),
       json_extract(value, '$.e')
FROM json_each(?2)
`;

function chunkArray<T>(items: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < items.length; i += size) out.push(items.slice(i, i + size));
  return out;
}

function encodeRowForInsert(row: AcceptedRow) {
  return {
    s: row.serviceId,
    n: row.serviceName,
    t: row.ts,
    d: row.day,
    a: row.agent,
    g: row.region,
    c: row.statusCode,
    k: row.statusClass,
    l: row.latencyMs,
    x: row.degraded ? 1 : 0,
    f: row.corrections.join(","),
  };
}

function encodeRejectedForInsert(row: RejectedRow) {
  return { n: row.lineNo, r: row.raw, e: row.reason };
}

export type OpenUploadResult = { uploadId: string };

export async function openUpload(env: Env, filename: string): Promise<OpenUploadResult> {
  const uploadId = crypto.randomUUID();
  await env.DB.prepare(
    `INSERT INTO uploads (id, filename, uploaded_at, status) VALUES (?1, ?2, ?3, 'open')`,
  )
    .bind(uploadId, filename, new Date().toISOString())
    .run();
  return { uploadId };
}

export type ChunkSummary = {
  rowsTotal: number;
  rowsAccepted: number;
  rowsCorrected: number;
  rowsRejected: number;
  rowsDuplicate: number;
};

export type PostChunkOutcome =
  | { ok: true; summary: ChunkSummary }
  | { ok: false; reason: "upload_not_found" | "upload_not_open" };

type LookupRow = {
  uploadStatus: string | null;
  priorRows: number;
  rowsTotal: number | null;
  rowsAccepted: number | null;
  rowsCorrected: number | null;
  rowsRejected: number | null;
  rowsDuplicate: number | null;
};

export async function postChunk(
  env: Env,
  uploadId: string,
  chunkIndex: number,
  chunkText: string,
): Promise<PostChunkOutcome> {
  const lookup = await env.DB.prepare(
    `SELECT u.status as uploadStatus, c.rows_total as rowsTotal, c.rows_accepted as rowsAccepted,
            c.rows_corrected as rowsCorrected, c.rows_rejected as rowsRejected,
            c.rows_duplicate as rowsDuplicate,
            -- Data rows recorded by every earlier chunk of this upload. Added to the
            -- within-chunk index so rejected_rows.line_no is the line number in the
            -- source file, which is the only number an auditor can look up. Summed
            -- from what was actually stored rather than assuming a chunk size, so the
            -- Worker keeps no opinion about how the client slices the file.
            (SELECT COALESCE(SUM(p.rows_total), 0) FROM upload_chunks p
              WHERE p.upload_id = u.id AND p.chunk_index < ?2) as priorRows
     FROM uploads u
     LEFT JOIN upload_chunks c ON c.upload_id = u.id AND c.chunk_index = ?2
     WHERE u.id = ?1`,
  )
    .bind(uploadId, chunkIndex)
    .first<LookupRow>();

  if (lookup === null) return { ok: false, reason: "upload_not_found" };
  if (lookup.uploadStatus !== "open") return { ok: false, reason: "upload_not_open" };

  if (lookup.rowsTotal !== null) {
    // This chunk index was already ingested - a client retry, not new work.
    // Re-running cleaning would double the upload_chunks row; return what's recorded.
    return {
      ok: true,
      summary: {
        rowsTotal: lookup.rowsTotal,
        rowsAccepted: lookup.rowsAccepted ?? 0,
        rowsCorrected: lookup.rowsCorrected ?? 0,
        rowsRejected: lookup.rowsRejected ?? 0,
        rowsDuplicate: lookup.rowsDuplicate ?? 0,
      },
    };
  }

  // The browser prepends the header line to every chunk (docs/decisions.md
  // section 4) so each chunk is self-describing; drop it here.
  // Split on \r?\n, not \n: all five source CSVs are CRLF, and splitting on \n
  // alone leaves a carriage return glued to the last column (region), which then
  // gets stored verbatim.
  const [, ...dataLines] = chunkText.split(/\r?\n/).filter((line) => line.length > 0);

  // +2 skips the header line and makes the count 1-based, matching what a text
  // editor shows; priorRows carries it across chunk boundaries.
  const firstLineNo = lookup.priorRows + 2;
  const results = dataLines.map((line, i) => cleanRow(line.split(","), firstLineNo + i, line));
  const accepted = results
    .filter((r): r is { accepted: true; row: AcceptedRow } => r.accepted)
    .map((r) => r.row);
  const rejected = results
    .filter((r): r is { accepted: false; row: RejectedRow } => !r.accepted)
    .map((r) => r.row);

  const { kept, duplicateCount: inChunkDuplicates } = dedupeAccepted(accepted);
  // Counted here, before the DB-level dedup below, rather than by re-querying which
  // specific rows D1 actually kept - see docs/decisions.md for why, and the bound.
  const correctedCount = kept.filter((row) => row.corrections.length > 0).length;

  const insertStatements = chunkArray(kept, INSERT_BATCH_SIZE).map((group) =>
    env.DB.prepare(INSERT_CHECKS_SQL).bind(uploadId, JSON.stringify(group.map(encodeRowForInsert))),
  );
  const rejectStatements = chunkArray(rejected, INSERT_BATCH_SIZE).map((group) =>
    env.DB.prepare(INSERT_REJECTED_SQL).bind(uploadId, JSON.stringify(group.map(encodeRejectedForInsert))),
  );

  let persisted = 0;
  if (insertStatements.length > 0) {
    const insertResults = await env.DB.batch(insertStatements);
    persisted = insertResults.reduce((sum, r) => sum + (r.meta.changes ?? 0), 0);
  }
  if (rejectStatements.length > 0) {
    await env.DB.batch(rejectStatements);
  }

  const dbDuplicates = kept.length - persisted;
  const summary: ChunkSummary = {
    rowsTotal: dataLines.length,
    rowsAccepted: persisted,
    rowsCorrected: correctedCount,
    rowsRejected: rejected.length,
    rowsDuplicate: inChunkDuplicates + dbDuplicates,
  };

  await env.DB.prepare(
    `INSERT INTO upload_chunks (upload_id, chunk_index, rows_total, rows_accepted,
                                rows_corrected, rows_rejected, rows_duplicate)
     VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)`,
  )
    .bind(
      uploadId,
      chunkIndex,
      summary.rowsTotal,
      summary.rowsAccepted,
      summary.rowsCorrected,
      summary.rowsRejected,
      summary.rowsDuplicate,
    )
    .run();

  return { ok: true, summary };
}

export type UploadSummary = {
  uploadId: string;
  status: "complete";
  dayFirst: string | null;
  dayLast: string | null;
  rowsTotal: number;
  rowsAccepted: number;
  rowsCorrected: number;
  rowsRejected: number;
  rowsDuplicate: number;
  corrections: Record<string, number>;
};

export type FinalizeOutcome =
  | { ok: true; summary: UploadSummary }
  | { ok: false; reason: "upload_not_found" | "upload_not_open" };

export async function finalizeUpload(env: Env, uploadId: string): Promise<FinalizeOutcome> {
  const upload = await env.DB.prepare(`SELECT status FROM uploads WHERE id = ?1`)
    .bind(uploadId)
    .first<{ status: string }>();
  if (upload === null) return { ok: false, reason: "upload_not_found" };
  if (upload.status !== "open") return { ok: false, reason: "upload_not_open" };

  const totals = await env.DB.prepare(
    `SELECT COALESCE(SUM(rows_total),0) as rowsTotal, COALESCE(SUM(rows_accepted),0) as rowsAccepted,
            COALESCE(SUM(rows_corrected),0) as rowsCorrected, COALESCE(SUM(rows_rejected),0) as rowsRejected,
            COALESCE(SUM(rows_duplicate),0) as rowsDuplicate
     FROM upload_chunks WHERE upload_id = ?1`,
  )
    .bind(uploadId)
    .first<{
      rowsTotal: number;
      rowsAccepted: number;
      rowsCorrected: number;
      rowsRejected: number;
      rowsDuplicate: number;
    }>();

  const dayRange = await env.DB.prepare(
    `SELECT MIN(day) as dayFirst, MAX(day) as dayLast FROM checks WHERE upload_id = ?1`,
  )
    .bind(uploadId)
    .first<{ dayFirst: string | null; dayLast: string | null }>();

  // Per-rule correction counts (uploads.corrections, docs/decisions.md section 5) are
  // grouped rather than scanned row by row - the distinct correction-string combinations
  // are few, so this is one cheap aggregate query over however many rows the upload has.
  const correctionGroups = await env.DB.prepare(
    `SELECT corrections, COUNT(*) as cnt FROM checks WHERE upload_id = ?1 AND corrections != '' GROUP BY corrections`,
  )
    .bind(uploadId)
    .all<{ corrections: string; cnt: number }>();

  const corrections: Record<string, number> = {};
  for (const group of correctionGroups.results) {
    for (const flag of group.corrections.split(",")) {
      corrections[flag] = (corrections[flag] ?? 0) + group.cnt;
    }
  }

  const dayFirst = dayRange?.dayFirst ?? null;
  const dayLast = dayRange?.dayLast ?? null;
  const rowsTotal = totals?.rowsTotal ?? 0;
  const rowsAccepted = totals?.rowsAccepted ?? 0;
  const rowsCorrected = totals?.rowsCorrected ?? 0;
  const rowsRejected = totals?.rowsRejected ?? 0;
  const rowsDuplicate = totals?.rowsDuplicate ?? 0;

  await env.DB.prepare(
    `UPDATE uploads SET status = 'complete', day_first = ?2, day_last = ?3,
            rows_total = ?4, rows_accepted = ?5, rows_corrected = ?6, rows_rejected = ?7,
            rows_duplicate = ?8, corrections = ?9
     WHERE id = ?1`,
  )
    .bind(
      uploadId,
      dayFirst,
      dayLast,
      rowsTotal,
      rowsAccepted,
      rowsCorrected,
      rowsRejected,
      rowsDuplicate,
      JSON.stringify(corrections),
    )
    .run();

  return {
    ok: true,
    summary: {
      uploadId,
      status: "complete",
      dayFirst,
      dayLast,
      rowsTotal,
      rowsAccepted,
      rowsCorrected,
      rowsRejected,
      rowsDuplicate,
      corrections,
    },
  };
}
